### ISSUE TITLE
Room Input Validation

### ISSUE THREAD

**Issue by jcr7467** [ECE-180D-WS-2022/Team3#37]
Right now, there is a weakness if two people 'create a game' from the python client, but pick the same RoomID to create. Fix this so it throws an error when creating a room that is already created by another user. 

Not a super high priority for now because I am assuming we will be the ones to use this, not general public. 
So, don't create 2 rooms with same roomID until this is fixed

**Comment by randallwc** [comment]
bump

**Comment by randallwc** [comment]
delete empty rooms
