### ISSUE TITLE
Make CamelCase member variables into snake_case

### ISSUE THREAD

**Issue by jcr7467** [ECE-180D-WS-2022/Team3#40]
inside gameMultiplayer.py and server.py

**Comment by randallwc** [comment]
![image](https://user-images.githubusercontent.com/15082470/157334483-8e858745-c48c-4bf9-8576-f1e5664629a6.png)

**Comment by randallwc** [comment]
https://www.jetbrains.com/help/pycharm/tutorial-code-quality-assistance-tips-and-tricks.html#5a3dcdbd
